#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#


obj-y  += ea_eeprom.o
obj-y  += ea_mac.o
obj-y  += ea_gpio_expander.o
obj-y  += mmc.o
obj-y  += ea_board.o

obj-$(CONFIG_EA_IMX_PTP)	+= ea_ptp.o

